import { 
  AuditResult, 
  MonitoredSite, 
  AgencyBranding, 
  UserAccount, 
  AdminTransaction, 
  BillingInvoice, 
  EmailTemplatePreview,
  PricingTier
} from '../types';

export const defaultAgencyBranding: AgencyBranding = {
  enabled: true,
  agencyName: 'Vanguard Digital Agency',
  tagline: 'Enterprise Web Strategy & WCAG Accessibility Compliance',
  primaryColor: '#2563EB',
  accentColor: '#10B981',
  contactEmail: 'audits@vanguarddigital.io',
  website: 'https://vanguarddigital.io',
  logoUrl: '',
  disclaimer: 'This audit report is generated by Vanguard Digital for our client. Recommendations adhere to W3C WCAG 2.2 AA guidelines and the European Accessibility Act (EAA).'
};

export const sampleAudits: Record<string, AuditResult> = {
  'example-ecommerce.com': {
    id: 'audit-ecom-001',
    url: 'https://www.luxe-apparel.store',
    timestamp: '2026-08-23 10:30 UTC',
    overallScore: 68,
    grade: 'Needs Remediation',
    status: 'warning',
    summary: 'The site has critical accessibility bottlenecks in primary conversion flows. Multiple product images lack descriptive alternative text, checkout button contrast fails WCAG 2.1 AA thresholds, and mobile modal drawers trap keyboard focus.',
    plainExecutiveSummary: 'Your online store currently scores 68/100, which puts your business at moderate legal risk under ADA Title III and the European Accessibility Act. While 22 components passed smoothly, 4 critical roadblocks are directly preventing blind and visually-impaired shoppers from completing checkout.',
    topPriorityFixes: [
      'Fix low-contrast "Add to Cart" and "Checkout" buttons so shoppers with low vision can find and click them.',
      'Add descriptive labels to 5 hero product images so screen-reader users know what products you sell.',
      'Ensure modal popups allow keyboard users to tab through and close them with the Escape key.'
    ],
    criticalCount: 4,
    moderateCount: 6,
    minorCount: 3,
    passedCount: 22,
    scannedElementsCount: 342,
    contrastPassRate: 74,
    ariaComplianceScore: 62,
    keyboardNavigableScore: 58,
    legalRiskLevel: 'High',
    issues: [
      {
        id: 'iss-1',
        category: 'contrast',
        severity: 'critical',
        title: 'Insufficient Color Contrast on "Add to Cart" Primary Button',
        plainSummary: 'Your main "Add to Cart" button uses light gray text on a pale background. This makes it almost invisible to over 15% of shoppers with visual impairments.',
        description: 'Text color #94A3B8 on background #F1F5F9 yields a contrast ratio of 2.14:1, which is below the minimum required 4.5:1 ratio for standard text.',
        wcagRule: 'WCAG 1.4.3 Contrast (Minimum)',
        wcagLevel: 'AA',
        affectedElement: 'button.btn-primary.add-to-cart',
        codeSnippetFaulty: '<button class="bg-slate-100 text-slate-400 font-semibold">\n  Add to Cart\n</button>',
        codeSnippetFix: '<button class="bg-blue-600 text-white font-semibold shadow-sm">\n  Add to Cart\n</button>',
        impact: 'Users with moderate visual impairments or color vision deficiencies cannot clearly read button labels.',
        howToFix: 'Increase the luminosity contrast between text and background to at least 4.5:1 for normal text and 3:1 for large text.'
      },
      {
        id: 'iss-2',
        category: 'images',
        severity: 'critical',
        title: 'Missing Alt Attributes on 5 Product Gallery Images',
        plainSummary: '5 images in your catalog are completely invisible to screen-reader users because they lack text descriptions.',
        description: 'Five key hero product images on the catalog page do not include alt attributes or descriptive text for screen readers.',
        wcagRule: 'WCAG 1.1.1 Non-text Content',
        wcagLevel: 'A',
        affectedElement: 'div.product-grid > img.gallery-thumb',
        codeSnippetFaulty: '<img src="/assets/products/leather-jacket.jpg" class="product-img" />',
        codeSnippetFix: '<img src="/assets/products/leather-jacket.jpg" alt="Men\'s vintage brown leather jacket with brass zippers" class="product-img" />',
        impact: 'Blind and low-vision users navigating via NVDA or VoiceOver hear only generic file paths instead of product details.',
        howToFix: 'Add informative, concise alt attributes describing the visual content of each product.'
      },
      {
        id: 'iss-3',
        category: 'keyboard',
        severity: 'critical',
        title: 'Keyboard Focus Trap Inside Quick-View Modal Drawer',
        plainSummary: 'When opening a product popup with a keyboard, users cannot tab back out or close it with the Escape key.',
        description: 'When keyboard focus enters the Quick-View product modal, focus cannot cycle to the close button or exit via the Escape key.',
        wcagRule: 'WCAG 2.1.2 No Keyboard Trap',
        wcagLevel: 'A',
        affectedElement: 'div.modal-backdrop#quick-view-modal',
        codeSnippetFaulty: '<div class="modal" tabIndex={-1}>\n  <div class="modal-content">...</div>\n</div>',
        codeSnippetFix: '<div role="dialog" aria-modal="true" aria-labelledby="modal-title" onKeyDown={handleKeyDown}>\n  <button aria-label="Close modal">×</button>\n</div>',
        impact: 'Motor-impaired and keyboard-only visitors become permanently stuck in the overlay and must force-refresh the page.',
        howToFix: 'Implement proper focus containment and attach an onKeyDown listener for the Escape key.'
      },
      {
        id: 'iss-4',
        category: 'forms',
        severity: 'critical',
        title: 'Missing Form Label on Checkout Promo Code Input',
        plainSummary: 'The promo discount input box has no text label. Blind customers will not know what to type in this box.',
        description: 'The discount coupon code input field lacks an associated <label> element or aria-label attribute.',
        wcagRule: 'WCAG 3.3.2 Labels or Instructions',
        wcagLevel: 'A',
        affectedElement: 'input#discount-code',
        codeSnippetFaulty: '<input type="text" id="discount-code" placeholder="Enter coupon..." />',
        codeSnippetFix: '<label for="discount-code" class="sr-only">Discount Code</label>\n<input type="text" id="discount-code" placeholder="Enter coupon..." aria-label="Discount Code" />',
        impact: 'Screen readers read this field as "unlabeled text edit box", causing confusion during checkout.',
        howToFix: 'Add a linked <label for="..."> or provide an aria-label attribute describing the field purpose.'
      },
      {
        id: 'iss-5',
        category: 'structure',
        severity: 'moderate',
        title: 'Skipped Heading Levels: H1 jumps directly to H4',
        plainSummary: 'Headings skip from level 1 straight to level 4, breaking the logical outline for assistive devices.',
        description: 'The page jumps from an <h1> main title directly into <h4> product card titles without intervening <h2> or <h3> headers.',
        wcagRule: 'WCAG 1.3.1 Info and Relationships',
        wcagLevel: 'A',
        affectedElement: 'section.featured-products > h4',
        codeSnippetFaulty: '<h1>Summer Collection</h1>\n<div class="items">\n  <h4>Breeze Linen Shirt</h4>\n</div>',
        codeSnippetFix: '<h1>Summer Collection</h1>\n<h2>Featured Products</h2>\n<div class="items">\n  <h3>Breeze Linen Shirt</h3>\n</div>',
        impact: 'Users navigating by heading outline lose context and hierarchy.',
        howToFix: 'Maintain sequential heading depth (H1 -> H2 -> H3) without skipping intermediate levels.'
      },
      {
        id: 'iss-6',
        category: 'aria',
        severity: 'moderate',
        title: 'Interactive Hamburger Button Missing ARIA Expanded State',
        plainSummary: 'The mobile navigation menu button does not announce whether the drawer is currently open or closed.',
        description: 'The mobile navigation trigger button does not toggle aria-expanded="true/false" upon interaction.',
        wcagRule: 'WCAG 4.1.2 Name, Role, Value',
        wcagLevel: 'AA',
        affectedElement: 'button#mobile-nav-toggle',
        codeSnippetFaulty: '<button id="mobile-nav-toggle" onClick="toggleMenu()">\n  <svg ... />\n</button>',
        codeSnippetFix: '<button id="mobile-nav-toggle" aria-expanded={isMenuOpen} aria-label="Toggle navigation menu" onClick="toggleMenu()">\n  <svg ... />\n</button>',
        impact: 'Non-visual users are unaware when navigation items appear on screen.',
        howToFix: 'Bind dynamic state to the aria-expanded attribute on disclosure triggers.'
      }
    ],
    checklist: [
      { id: 'chk-1', task: 'Increase button contrast on "Add to Cart" and "Checkout" to >= 4.5:1 ratio', wcagRule: '1.4.3', severity: 'critical', completed: false, estimatedMinutes: 15 },
      { id: 'chk-2', task: 'Add descriptive alt text to all 5 hero catalog images', wcagRule: '1.1.1', severity: 'critical', completed: false, estimatedMinutes: 20 },
      { id: 'chk-3', task: 'Trap focus and support Escape key dismissal on Quick-View modal drawer', wcagRule: '2.1.2', severity: 'critical', completed: false, estimatedMinutes: 45 },
      { id: 'chk-4', task: 'Link <label for="discount-code"> to coupon input in checkout funnel', wcagRule: '3.3.2', severity: 'critical', completed: false, estimatedMinutes: 10 },
      { id: 'chk-5', task: 'Reorganize page heading hierarchy into valid H1 -> H2 -> H3 sequence', wcagRule: '1.3.1', severity: 'moderate', completed: false, estimatedMinutes: 25 },
      { id: 'chk-6', task: 'Bind aria-expanded state to mobile hamburger menu button', wcagRule: '4.1.2', severity: 'moderate', completed: false, estimatedMinutes: 15 }
    ]
  },
  'startup-saas.io': {
    id: 'audit-saas-002',
    url: 'https://cloudflow-analytics.io',
    timestamp: '2026-08-22 14:15 UTC',
    overallScore: 84,
    grade: 'AA',
    status: 'passed',
    summary: 'Strong foundational accessibility architecture. Headings and landmarks are properly configured. Minor improvements needed in keyboard focus rings and dark mode muted text contrast.',
    plainExecutiveSummary: 'Cloudflow Analytics scores a solid 84/100, meeting WCAG 2.2 Level AA conformance standards for most user journeys. Only minor visual contrast enhancements in dark mode and focus ring visibility remain.',
    topPriorityFixes: [
      'Sharpen dark mode text contrast on secondary documentation pages.',
      'Make keyboard focus outline rings thicker and more visible on dark backgrounds.',
      'Add table header scope identifiers to pricing comparison charts.'
    ],
    criticalCount: 1,
    moderateCount: 3,
    minorCount: 4,
    passedCount: 29,
    scannedElementsCount: 280,
    contrastPassRate: 88,
    ariaComplianceScore: 92,
    keyboardNavigableScore: 86,
    legalRiskLevel: 'Low',
    issues: [
      {
        id: 'iss-saas-1',
        category: 'keyboard',
        severity: 'critical',
        title: 'Focus Indicator Suppressed via outline:none in Global Stylesheet',
        plainSummary: 'Keyboard users cannot see a colored focus outline when tabbing through main navigation links.',
        description: 'Global CSS rule a:focus { outline: none } removes the visible focus indicator without a custom replacement.',
        wcagRule: 'WCAG 2.4.7 Focus Visible',
        wcagLevel: 'AA',
        affectedElement: 'nav.main-nav a',
        codeSnippetFaulty: 'a:focus { outline: none; }',
        codeSnippetFix: 'a:focus-visible { outline: 2px solid #2563EB; outline-offset: 2px; }',
        impact: 'Keyboard navigation becomes completely invisible for sighted keyboard users.',
        howToFix: 'Ensure all focusable elements maintain a distinct, visible outline or background highlight on :focus-visible.'
      }
    ],
    checklist: [
      { id: 'chk-s1', task: 'Remove outline:none and provide custom 2px focus rings', wcagRule: '2.4.7', severity: 'critical', completed: true, estimatedMinutes: 20 },
      { id: 'chk-s2', task: 'Boost footer link gray contrast to #CBD5E1', wcagRule: '1.4.3', severity: 'moderate', completed: false, estimatedMinutes: 10 }
    ]
  },
  'healthclinic-portal.org': {
    id: 'audit-health-003',
    url: 'https://metrohealth-care.org',
    timestamp: '2026-08-21 09:00 UTC',
    overallScore: 54,
    grade: 'Needs Remediation',
    status: 'failed',
    summary: 'Substantial Section 508 / HHS compliance risk. Appointment booking form errors are not announced to screen readers, and patient intake PDF documents lack semantic structural tags.',
    plainExecutiveSummary: 'MetroHealth Care Portal currently scores 54/100, which creates immediate non-compliance risk under Section 508 and HHS healthcare guidelines. Patients using assistive devices are unable to complete online appointment bookings without assistance.',
    topPriorityFixes: [
      'Connect error notifications in the appointment booking flow to aria-live polite regions.',
      'Add required field indicators and programmatic labels to doctor selection dropdowns.',
      'Provide alternative accessible appointment request methods for urgent patients.'
    ],
    criticalCount: 7,
    moderateCount: 8,
    minorCount: 5,
    passedCount: 14,
    scannedElementsCount: 410,
    contrastPassRate: 58,
    ariaComplianceScore: 49,
    keyboardNavigableScore: 52,
    legalRiskLevel: 'High',
    issues: [
      {
        id: 'iss-health-1',
        category: 'forms',
        severity: 'critical',
        title: 'Appointment Booking Form Validation Errors Not Announced via ARIA Live',
        plainSummary: 'When a patient submits the booking form with missing fields, the red error text is not read out loud by screen readers.',
        description: 'Inline validation error messages inserted into the DOM lack role="alert" or aria-live="assertive" attributes.',
        wcagRule: 'WCAG 3.3.1 Error Identification',
        wcagLevel: 'A',
        affectedElement: 'div#booking-errors-container',
        codeSnippetFaulty: '<div class="error-msg">Please select an appointment time</div>',
        codeSnippetFix: '<div role="alert" aria-live="assertive" class="error-msg">\n  Please select an appointment time\n</div>',
        impact: 'Patients who are blind or use screen readers submit the form but receive no audible feedback explaining why nothing happened.',
        howToFix: 'Wrap dynamic error banners in an aria-live region so assistive software speaks the message immediately.'
      }
    ],
    checklist: [
      { id: 'chk-h1', task: 'Add role="alert" to appointment validation error container', wcagRule: '3.3.1', severity: 'critical', completed: false, estimatedMinutes: 25 },
      { id: 'chk-h2', task: 'Ensure all doctor specialty icons have text fallback', wcagRule: '1.1.1', severity: 'critical', completed: false, estimatedMinutes: 30 }
    ]
  }
};

export const sampleMonitoredSites: MonitoredSite[] = [
  {
    id: 'site-1',
    url: 'https://www.luxe-apparel.store',
    name: 'Luxe Apparel Store',
    lastScanned: '2 hours ago',
    score: 68,
    previousScore: 62,
    status: 'improved',
    criticalIssues: 4,
    monitoringInterval: 'daily',
    notificationsEnabled: true,
    scoreHistory: [
      { date: 'Aug 01', score: 58 },
      { date: 'Aug 08', score: 62 },
      { date: 'Aug 15', score: 62 },
      { date: 'Aug 23', score: 68 },
    ]
  },
  {
    id: 'site-2',
    url: 'https://cloudflow-analytics.io',
    name: 'Cloudflow Analytics SaaS',
    lastScanned: 'Yesterday',
    score: 84,
    previousScore: 84,
    status: 'stable',
    criticalIssues: 1,
    monitoringInterval: 'weekly',
    notificationsEnabled: true,
    scoreHistory: [
      { date: 'Aug 01', score: 80 },
      { date: 'Aug 08', score: 82 },
      { date: 'Aug 15', score: 84 },
      { date: 'Aug 23', score: 84 },
    ]
  },
  {
    id: 'site-3',
    url: 'https://metrohealth-care.org',
    name: 'MetroHealth Patient Portal',
    lastScanned: '3 days ago',
    score: 54,
    previousScore: 59,
    status: 'declined',
    criticalIssues: 7,
    monitoringInterval: 'daily',
    notificationsEnabled: true,
    scoreHistory: [
      { date: 'Aug 01', score: 62 },
      { date: 'Aug 08', score: 60 },
      { date: 'Aug 15', score: 59 },
      { date: 'Aug 23', score: 54 },
    ]
  }
];

export const samplePricingTiers: PricingTier[] = [
  {
    id: 'tier-free',
    name: 'Free Scan',
    tier: 'free',
    description: 'Instant accessibility health score and high-level compliance summary.',
    priceMonthly: 0,
    priceAnnual: 0,
    features: [
      'Executive Summary report card',
      'Overall 0-100 WCAG health score',
      'Issue count breakdown by severity',
      'WCAG 2.2 Level A/AA basic check',
      'Locked technical issue previews',
      'Single URL manual scans'
    ],
    ctaText: 'Run Free Scan'
  },
  {
    id: 'tier-pro',
    name: 'Pro Compliance',
    tier: 'pro',
    badge: 'Most Popular',
    popular: true,
    description: 'For business owners, developers, and compliance managers needing full technical remediation.',
    priceMonthly: 49,
    priceAnnual: 39,
    features: [
      'Complete Unlocked PDF Audit Report',
      'Plain-language executive summary',
      'Full technical code snippets & fixes',
      'Interactive Developer Checklist',
      'Continuous daily automated monitoring',
      'Instant regression email notifications',
      'Up to 3 production website domains'
    ],
    ctaText: 'Get Pro Report'
  },
  {
    id: 'tier-agency',
    name: 'Agency White-Label',
    tier: 'agency',
    badge: 'Agencies & Consultants',
    isAgency: true,
    description: 'For digital agencies, web design shops, and consulting firms serving multiple client brands.',
    priceMonthly: 149,
    priceAnnual: 119,
    features: [
      'Everything in Pro Compliance',
      '100% White-Label PDF Branding (Logo, Colors)',
      'Multi-site client comparison reports',
      'Priority-ranked remediation roadmaps',
      'Unlimited client website domains',
      'Client portal sharing & CSV exports',
      'Dedicated compliance specialist support'
    ],
    ctaText: 'Start Agency Plan'
  }
];

export const sampleUserAccounts: UserAccount[] = [
  {
    id: 'usr-1',
    name: 'Alex Rivera',
    email: 'admin@vanguarddigital.io',
    role: 'admin',
    plan: 'agency',
    billingCycle: 'annual',
    status: 'Active',
    currentPeriodEnd: 'Sep 24, 2027',
    cancelAtPeriodEnd: false,
    cardLast4: '4242',
    cardBrand: 'Visa',
    signupDate: 'Jan 15, 2026',
    totalScansCount: 148,
    overrideNote: 'Enterprise agency partner with custom branding'
  },
  {
    id: 'usr-2',
    name: 'Sarah Chen',
    email: 'sarah@luxe-apparel.store',
    role: 'user',
    plan: 'pro',
    billingCycle: 'monthly',
    status: 'Active',
    currentPeriodEnd: 'Sep 18, 2026',
    cancelAtPeriodEnd: false,
    cardLast4: '8831',
    cardBrand: 'Mastercard',
    signupDate: 'May 04, 2026',
    totalScansCount: 42
  },
  {
    id: 'usr-3',
    name: 'Marcus Brody',
    email: 'marcus@cloudflow.io',
    role: 'user',
    plan: 'pro',
    billingCycle: 'annual',
    status: 'Past Due',
    currentPeriodEnd: 'Aug 20, 2026',
    cancelAtPeriodEnd: false,
    cardLast4: '1092',
    cardBrand: 'Amex',
    signupDate: 'Feb 12, 2026',
    totalScansCount: 65,
    overrideNote: 'Card expired on last renewal attempt'
  },
  {
    id: 'usr-4',
    name: 'Elena Rostova',
    email: 'elena@metrohealth-care.org',
    role: 'user',
    plan: 'free',
    billingCycle: 'monthly',
    status: 'Active',
    currentPeriodEnd: 'N/A',
    cancelAtPeriodEnd: false,
    cardLast4: 'None',
    cardBrand: 'N/A',
    signupDate: 'Aug 10, 2026',
    totalScansCount: 8
  },
  {
    id: 'usr-5',
    name: 'Devon Vance',
    email: 'devon@vancestrategy.co',
    role: 'user',
    plan: 'agency',
    billingCycle: 'monthly',
    status: 'Comped',
    currentPeriodEnd: 'Dec 31, 2026',
    cancelAtPeriodEnd: false,
    cardLast4: 'None',
    cardBrand: 'Comped',
    signupDate: 'Jun 22, 2026',
    totalScansCount: 94,
    overrideNote: 'Complimentary trial for accessibility webinar speaker'
  }
];

export const sampleAdminTransactions: AdminTransaction[] = [
  {
    id: 'tx-901',
    date: 'Aug 24, 2026',
    customerId: 'usr-1',
    customerName: 'Alex Rivera',
    customerEmail: 'admin@vanguarddigital.io',
    amount: 1428.00,
    plan: 'Agency White-Label (Annual)',
    status: 'Succeeded'
  },
  {
    id: 'tx-902',
    date: 'Aug 22, 2026',
    customerId: 'usr-2',
    customerName: 'Sarah Chen',
    customerEmail: 'sarah@luxe-apparel.store',
    amount: 49.00,
    plan: 'Pro Compliance (Monthly)',
    status: 'Succeeded'
  },
  {
    id: 'tx-903',
    date: 'Aug 20, 2026',
    customerId: 'usr-3',
    customerName: 'Marcus Brody',
    customerEmail: 'marcus@cloudflow.io',
    amount: 468.00,
    plan: 'Pro Compliance (Annual)',
    status: 'Failed'
  },
  {
    id: 'tx-904',
    date: 'Aug 14, 2026',
    customerId: 'usr-6',
    customerName: 'Claire Dupont',
    customerEmail: 'claire@dupontmedia.fr',
    amount: 149.00,
    plan: 'Agency White-Label (Monthly)',
    status: 'Refunded',
    refundReason: 'Accidental duplicate charge approved by support'
  },
  {
    id: 'tx-905',
    date: 'Aug 10, 2026',
    customerId: 'usr-7',
    customerName: 'Liam O\'Connor',
    customerEmail: 'liam@dublindesign.ie',
    amount: 49.00,
    plan: 'Pro Compliance (Monthly)',
    status: 'Succeeded'
  }
];

export const sampleBillingInvoices: BillingInvoice[] = [
  {
    id: 'inv-2026-08',
    date: 'Aug 24, 2026',
    amount: 119.00,
    planName: 'Agency White-Label Plan',
    status: 'Paid',
    pdfDownloadUrl: '#'
  },
  {
    id: 'inv-2026-07',
    date: 'Jul 24, 2026',
    amount: 119.00,
    planName: 'Agency White-Label Plan',
    status: 'Paid',
    pdfDownloadUrl: '#'
  },
  {
    id: 'inv-2026-06',
    date: 'Jun 24, 2026',
    amount: 119.00,
    planName: 'Agency White-Label Plan',
    status: 'Paid',
    pdfDownloadUrl: '#'
  }
];

export const sampleEmailTemplates: EmailTemplatePreview[] = [
  // User Emails
  {
    id: 'email-user-welcome',
    target: 'user',
    title: 'User Welcome Email',
    subject: 'Welcome to AccessAudit — Your Accessibility Command Center',
    trigger: 'Sent immediately after user registration / plan activation',
    description: 'Welcomes new subscribers, highlights their plan entitlements, and guides them through their first scan.',
    ctaText: 'Go to Your Dashboard',
    bodyPreview: [
      'Hi Alex,',
      'Welcome to AccessAudit! Your Agency White-Label subscription is now fully active.',
      'Here is what is unlocked on your account:',
      '• Unlimited W3C WCAG 2.2 AA / ADA compliance scans',
      '• White-label PDF export with Vanguard Digital Agency branding',
      '• Automated continuous monitoring and instant regression alerts',
      'Ready to inspect your first client site? Click below to launch your command center.'
    ]
  },
  {
    id: 'email-user-receipt',
    target: 'user',
    title: 'Payment Receipt / Invoice',
    subject: 'Receipt for your AccessAudit subscription (#INV-2026-08)',
    trigger: 'Sent upon every successful monthly/annual subscription payment',
    description: 'Provides a clean financial summary, payment method verification, and downloadable PDF invoice link.',
    ctaText: 'Download PDF Invoice',
    bodyPreview: [
      'Hi Alex,',
      'Thank you for your payment! We have charged $119.00 to your Visa ending in 4242 for your Agency White-Label Plan.',
      'Invoice Number: INV-2026-08',
      'Billing Period: Aug 24, 2026 – Sep 24, 2026',
      'You can download your full tax invoice or manage your payment preferences anytime in your Billing Settings.'
    ]
  },
  {
    id: 'email-user-scan-ready',
    target: 'user',
    title: 'Scan Complete Notification',
    subject: 'Your accessibility report for https://www.luxe-apparel.store is ready',
    trigger: 'Sent after an on-demand or automated deep scan finishes processing',
    description: 'Summarizes the overall score, severity count traffic lights, and direct PDF download link.',
    ctaText: 'View Full Audit & Code Fixes',
    bodyPreview: [
      'Hi Alex,',
      'Your deep scan for https://www.luxe-apparel.store has completed with an overall score of 68/100.',
      'Traffic-Light Severity Summary:',
      '🔴 4 Critical Blockers (WCAG Level A)',
      '🟡 6 Moderate Warnings (WCAG Level AA)',
      '🟢 22 Passed Criteria',
      'Click below to inspect the interactive remediation roadmap and copy ready-to-use code patches.'
    ]
  },
  {
    id: 'email-user-monthly-digest',
    target: 'user',
    title: 'Monthly Monitoring Digest',
    subject: 'August Accessibility Digest — Score changed +6% across your portfolio',
    trigger: 'Sent on the 1st of every month summarizing monitored site trends',
    description: 'Aggregates multi-site compliance improvements, regressions, and resolved issues for clients.',
    ctaText: 'View Monthly Portfolio Trends',
    bodyPreview: [
      'Hi Alex,',
      'Here is your monthly accessibility progress summary for August 2026 across 3 monitored domains:',
      '• Luxe Apparel: 68/100 (+6% improvement)',
      '• Cloudflow Analytics: 84/100 (Stable Level AA)',
      '• MetroHealth Portal: 54/100 (Regressed -5%, action needed)',
      'Keep up the great momentum! Your active monitoring prevented 3 regressions from reaching live shoppers.'
    ]
  },
  {
    id: 'email-user-payment-failed',
    target: 'user',
    title: 'Payment Failed / Card Declined',
    subject: 'Urgent: Update payment method to maintain your AccessAudit monitoring',
    trigger: 'Sent when a recurring subscription renewal fails (e.g. card expired)',
    description: 'Polite, clear warning informing the user that their plan is in grace period with a direct update link.',
    ctaText: 'Update Payment Method',
    bodyPreview: [
      'Hi Alex,',
      'We were unable to process your recent renewal payment of $119.00 using your Visa ending in 4242.',
      'Don\'t worry — your white-label reports and automated monitoring remain active for the next 7 days.',
      'Please update your payment method to ensure continuous monitoring and prevent service interruption.'
    ]
  },
  {
    id: 'email-user-cancelled',
    target: 'user',
    title: 'Subscription Cancelled Confirmation',
    subject: 'Confirmation of cancellation — AccessAudit Pro Plan',
    trigger: 'Sent immediately when a user cancels their paid plan',
    description: 'Confirms cancellation terms, reinforces that access remains until the end of the paid cycle, and provides reactivation CTA.',
    ctaText: 'Reactivate Subscription Anytime',
    bodyPreview: [
      'Hi Alex,',
      'We have received your cancellation request. Your Agency White-Label plan will not renew after September 24, 2026.',
      'You will retain full access to all white-label PDF downloads and unlimited scans until your current billing period ends.',
      'If you ever wish to resume, your audit history and custom branding presets will be saved.'
    ]
  },
  {
    id: 'email-user-renewal-reminder',
    target: 'user',
    title: 'Annual Renewal Reminder',
    subject: 'Upcoming renewal notice for your AccessAudit Annual Plan (in 3 days)',
    trigger: 'Sent 3 days prior to an annual subscription renewal charge',
    description: 'Transparent billing notice required by modern consumer and business subscription compliance.',
    ctaText: 'Review Billing Preferences',
    bodyPreview: [
      'Hi Alex,',
      'This is a friendly reminder that your AccessAudit Annual Plan is scheduled to renew on September 24, 2026 for $1,428.00.',
      'Payment will be billed to your Visa card ending in 4242.',
      'No action is required if you wish to keep your continuous monitoring and agency tools active.'
    ]
  },
  // Admin Emails
  {
    id: 'email-admin-new-sub',
    target: 'admin',
    title: 'New Subscriber Notification (Admin)',
    subject: '[Admin Alert] New Agency Subscriber: Vanguard Digital ($1,428/yr)',
    trigger: 'Sent to system admins when a customer purchases a paid tier',
    description: 'Internal operational notification displaying customer revenue, plan choice, and account creation details.',
    ctaText: 'View Customer in Admin CRM',
    bodyPreview: [
      'New Subscription Activated:',
      'Customer: Alex Rivera (admin@vanguarddigital.io)',
      'Plan: Agency White-Label (Annual)',
      'MRR Impact: +$119.00/mo (Gross: $1,428.00 upfront)',
      'Signup Source: Organic Landing Page -> URL Scan',
      'Log into the Admin Panel to review customer profile or view scan telemetry.'
    ]
  },
  {
    id: 'email-admin-failed-charge',
    target: 'admin',
    title: 'Failed Payment Alert (Admin)',
    subject: '[Admin Alert] Subscription Renewal Failed: Cloudflow SaaS ($468.00)',
    trigger: 'Sent to system admins when a renewal fails, allowing proactive account team outreach',
    description: 'Enables customer success and admin teams to intervene before involuntary churn.',
    ctaText: 'Open Customer Account',
    bodyPreview: [
      'Payment Failure Alert:',
      'Customer: Marcus Brody (marcus@cloudflow.io)',
      'Plan: Pro Compliance Annual ($468.00)',
      'Failure Code: card_declined / insufficient_funds',
      'Retry Attempt: 1 of 3 (Next retry in 48 hours)',
      'Grace Period: Active through Aug 27, 2026.'
    ]
  },
  {
    id: 'email-admin-weekly-digest',
    target: 'admin',
    title: 'Weekly Executive Admin Digest',
    subject: '[Weekly Metrics] AccessAudit MRR: $18,420 (+12%) | 14 New Subscribers',
    trigger: 'Sent every Monday morning to executive and engineering leads',
    description: 'High-level business telemetry covering revenue, churn, conversion rates, and total scanned URLs.',
    ctaText: 'Open Admin Analytics',
    bodyPreview: [
      'AccessAudit Weekly Operations Snapshot:',
      '• Monthly Recurring Revenue (MRR): $18,420 (+12.4% WoW)',
      '• New Paid Subscriptions: 14 (8 Pro, 6 Agency)',
      '• Churn Rate: 1.4% (Industry benchmark: <3%)',
      '• Total URLs Audited: 1,482 scans performed',
      '• Average Compliance Score Lift: +14 points across monitored client sites.'
    ]
  }
];
